// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import query "github.com/jozuenoon/message_bus/query"
import time "time"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetEvents provides a mock function with given fields: ctx, detectors, before, after, limit
func (_m *Repository) GetEvents(ctx context.Context, detectors []string, before time.Time, after time.Time, limit int64) []*query.Event {
	ret := _m.Called(ctx, detectors, before, after, limit)

	var r0 []*query.Event
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, int64) []*query.Event); ok {
		r0 = rf(ctx, detectors, before, after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*query.Event)
		}
	}

	return r0
}
