# https://goreleaser.com/customization/
builds:
  - id: cqserver
    binary: cqserver
    main: ./cmd/cq/main.go
    goos: [freebsd, windows, linux, darwin]
    goarch: [amd64, arm, arm64]
    goarm: [6, 7]
    ignore:
      - { goos: darwin, goarch: 386 }
      - { goos: linux, goarch: arm, goarm: 7 }

  - id: mbcli
      binary: mbcli
      main: ./mbcli/main.go
      goos: [freebsd, windows, linux, darwin]
      goarch: [amd64, arm, arm64]
      goarm: [6, 7]
      ignore:
        - { goos: darwin, goarch: 386 }
        - { goos: linux, goarch: arm, goarm: 7 }

archives:
  - id: servers
    builds: [cqserver]
    format: binary
  - id: mbcli
    builds: [mbcli]
    format: binary