version: '3'

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.3
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd'
      - '--initial-advertise-peer-urls=http://etcd:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd:2379,http://127.0.0.1:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd=http://etcd:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2379:2379"
    volumes:
      - etcd:/etcd_data


volumes:
  etcd: