kind: ConfigMap
apiVersion: v1
metadata:
    name: "{{ .Release.Name }}"
    namespace: {{ .Values.namespace }}
data:
    config.yaml: |-
        collector_port: {{.Values.CollectorPort}}
        query_port: {{.Values.QueryPort}}
        healthcheck_port: {{.Values.HealthCheckPort}}
        etcd:
          endpoints: {{.Values.ETCDEndpoints}}
