apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}"
  annotations:
    helm.sh/created: {{ .Release.Time.Seconds | quote }}
    # Memo for stream timeout configuration: https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/grpc#notes-on-using-responserequest-streams
    kubernetes.io/ingress.class: {{ .Values.IngressClass }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    # We get unencrypted traffic inside cluster, to use TLS also internally we need to enable
    # annotation below + provide TLS configuration into our service accordingly.
    # nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - "{{ .Values.FQDN }}"
    secretName: {{ .Values.FQDN | replace "." "-"}}-tls-cert
  rules:
  - host: "{{ .Values.FQDN }}"
    http:
      paths:
      - path: /query.QueryService
        backend:
          serviceName: "{{ .Release.Name }}"
          servicePort: {{ .Values.QueryPort }}
      - path: /collector.CollectorService
        backend:
          serviceName: "{{ .Release.Name }}"
          servicePort: {{ .Values.CollectorPort }}
