apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: "{{ .Release.Name }}"
    annotations:
        helm.sh/created: {{.Release.Time.Seconds | quote }}
    labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}"
spec:
    selector:
        matchLabels:
            component: "{{.Release.Name}}"
        {{- if .Values.MinAvailable}}
    minAvailable: {{.Values.MinAvailable}}
        {{- else}}
    minAvailable: 1
        {{- end}}