apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}"
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - name: collector
      protocol: TCP
      port: {{.Values.CollectorPort}}
      targetPort: {{.Values.CollectorPort}}
    - name: query
      protocol: TCP
      port: {{.Values.QueryPort}}
      targetPort: {{.Values.QueryPort}}
    - name: healthcheck
      protocol: TCP
      port: {{.Values.HealthCheckPort}}
      targetPort: {{.Values.HealthCheckPort}}