// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package query

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DetectionEvent struct {
	Time []*timestamp.Timestamp `protobuf:"bytes,1,rep,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to DeviceId:
	//	*DetectionEvent_WifiMac
	//	*DetectionEvent_BluetoothMac
	//	*DetectionEvent_MobileImsi
	DeviceId             isDetectionEvent_DeviceId `protobuf_oneof:"device_id"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DetectionEvent) Reset()         { *m = DetectionEvent{} }
func (m *DetectionEvent) String() string { return proto.CompactTextString(m) }
func (*DetectionEvent) ProtoMessage()    {}
func (*DetectionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *DetectionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionEvent.Unmarshal(m, b)
}
func (m *DetectionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionEvent.Marshal(b, m, deterministic)
}
func (m *DetectionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionEvent.Merge(m, src)
}
func (m *DetectionEvent) XXX_Size() int {
	return xxx_messageInfo_DetectionEvent.Size(m)
}
func (m *DetectionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionEvent proto.InternalMessageInfo

func (m *DetectionEvent) GetTime() []*timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type isDetectionEvent_DeviceId interface {
	isDetectionEvent_DeviceId()
}

type DetectionEvent_WifiMac struct {
	WifiMac string `protobuf:"bytes,2,opt,name=wifi_mac,json=wifiMac,proto3,oneof"`
}

type DetectionEvent_BluetoothMac struct {
	BluetoothMac string `protobuf:"bytes,3,opt,name=bluetooth_mac,json=bluetoothMac,proto3,oneof"`
}

type DetectionEvent_MobileImsi struct {
	MobileImsi string `protobuf:"bytes,4,opt,name=mobile_imsi,json=mobileImsi,proto3,oneof"`
}

func (*DetectionEvent_WifiMac) isDetectionEvent_DeviceId() {}

func (*DetectionEvent_BluetoothMac) isDetectionEvent_DeviceId() {}

func (*DetectionEvent_MobileImsi) isDetectionEvent_DeviceId() {}

func (m *DetectionEvent) GetDeviceId() isDetectionEvent_DeviceId {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *DetectionEvent) GetWifiMac() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_WifiMac); ok {
		return x.WifiMac
	}
	return ""
}

func (m *DetectionEvent) GetBluetoothMac() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_BluetoothMac); ok {
		return x.BluetoothMac
	}
	return ""
}

func (m *DetectionEvent) GetMobileImsi() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_MobileImsi); ok {
		return x.MobileImsi
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DetectionEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DetectionEvent_WifiMac)(nil),
		(*DetectionEvent_BluetoothMac)(nil),
		(*DetectionEvent_MobileImsi)(nil),
	}
}

type Range struct {
	After                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	Before               *timestamp.Timestamp `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetAfter() *timestamp.Timestamp {
	if m != nil {
		return m.After
	}
	return nil
}

func (m *Range) GetBefore() *timestamp.Timestamp {
	if m != nil {
		return m.Before
	}
	return nil
}

type GetEventsRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	DetectorIds          []string `protobuf:"bytes,2,rep,name=detector_ids,json=detectorIds,proto3" json:"detector_ids,omitempty"`
	Range                *Range   `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetEventsRequest) GetDetectorIds() []string {
	if m != nil {
		return m.DetectorIds
	}
	return nil
}

func (m *GetEventsRequest) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

type GetEventsResponse struct {
	Events               []*DetectionEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*DetectionEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*DetectionEvent)(nil), "queryserver.DetectionEvent")
	proto.RegisterType((*Range)(nil), "queryserver.Range")
	proto.RegisterType((*GetEventsRequest)(nil), "queryserver.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "queryserver.GetEventsResponse")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x5d, 0xef, 0xd2, 0x30,
	0x14, 0xc6, 0xdd, 0x7f, 0x0c, 0xdd, 0x19, 0xbe, 0x35, 0x5e, 0x2c, 0x10, 0x75, 0x2c, 0x31, 0xd9,
	0xd5, 0x20, 0xe3, 0x1b, 0x18, 0x8d, 0x60, 0x62, 0x8c, 0xc5, 0xfb, 0x65, 0x2f, 0x67, 0xd8, 0x64,
	0x5d, 0xa1, 0xed, 0x30, 0x7e, 0x26, 0x6f, 0xfd, 0x80, 0x66, 0xdd, 0x20, 0x60, 0x22, 0x5c, 0xf6,
	0xe9, 0xaf, 0x4f, 0x9f, 0x73, 0x1e, 0xf0, 0x0e, 0x2d, 0xca, 0x5f, 0xf1, 0x5e, 0x0a, 0x2d, 0x48,
	0x7f, 0x50, 0x28, 0x8f, 0x28, 0xa7, 0x6f, 0x77, 0x42, 0xec, 0x6a, 0x5c, 0x98, 0xab, 0xbc, 0xad,
	0x16, 0x9a, 0x71, 0x54, 0x3a, 0xe3, 0xfb, 0x9e, 0x0e, 0xff, 0x58, 0xf0, 0xec, 0x03, 0x6a, 0x2c,
	0x34, 0x13, 0xcd, 0xc7, 0x23, 0x36, 0x9a, 0xc4, 0x30, 0xea, 0x28, 0xdf, 0x0a, 0xec, 0xc8, 0x4b,
	0xa6, 0x71, 0x6f, 0x11, 0x9f, 0x2c, 0xe2, 0xef, 0x27, 0x0b, 0x6a, 0x38, 0x32, 0x83, 0x27, 0x3f,
	0x59, 0xc5, 0x52, 0x9e, 0x15, 0xfe, 0x43, 0x60, 0x45, 0xee, 0xfa, 0x11, 0x7d, 0xdc, 0x29, 0x5f,
	0xb2, 0x82, 0xbc, 0x83, 0xa7, 0x79, 0xdd, 0xa2, 0x16, 0x42, 0xff, 0x30, 0x84, 0x3d, 0x10, 0x93,
	0xb3, 0xdc, 0x61, 0x73, 0xf0, 0xb8, 0xc8, 0x59, 0x8d, 0x29, 0xe3, 0x8a, 0xf9, 0xa3, 0x01, 0x82,
	0x5e, 0xdc, 0x70, 0xc5, 0xde, 0x7b, 0xe0, 0x96, 0x78, 0x64, 0x05, 0xa6, 0xac, 0x0c, 0x39, 0x38,
	0x34, 0x6b, 0x76, 0x48, 0x96, 0xe0, 0x64, 0x95, 0x46, 0xe9, 0x5b, 0x81, 0x75, 0x27, 0x6d, 0x0f,
	0x92, 0x04, 0xc6, 0x39, 0x56, 0x42, 0xa2, 0x09, 0x7b, 0xfb, 0xc9, 0x40, 0x86, 0x2d, 0xbc, 0xf8,
	0x84, 0xda, 0xac, 0x47, 0x51, 0x3c, 0xb4, 0xa8, 0x34, 0x79, 0x05, 0x4e, 0xcd, 0x38, 0xd3, 0xe6,
	0x67, 0x9b, 0xf6, 0x07, 0x32, 0x87, 0x49, 0x69, 0xd6, 0x29, 0x64, 0xca, 0x4a, 0xe5, 0x3f, 0x04,
	0x76, 0xe4, 0x52, 0xef, 0xa4, 0x6d, 0x4a, 0x45, 0x22, 0x70, 0x64, 0x97, 0xdd, 0xac, 0xc2, 0x4b,
	0x48, 0x7c, 0x51, 0x58, 0x6c, 0xa6, 0xa2, 0x3d, 0x10, 0xae, 0xe1, 0xe5, 0xc5, 0xb7, 0x6a, 0x2f,
	0x1a, 0x85, 0x64, 0x05, 0x63, 0x34, 0xca, 0x50, 0xd0, 0xec, 0xea, 0xfd, 0x75, 0x97, 0x74, 0x40,
	0x93, 0xdf, 0x16, 0x4c, 0xbe, 0x75, 0xd8, 0x16, 0x65, 0xb7, 0x43, 0xf2, 0x19, 0xdc, 0xb3, 0x35,
	0x79, 0x7d, 0x65, 0xf1, 0xef, 0xa4, 0xd3, 0x37, 0xff, 0xbb, 0x1e, 0x12, 0x7d, 0x85, 0xe7, 0x67,
	0x71, 0xab, 0x25, 0x66, 0xfc, 0x9e, 0xe3, 0xad, 0xcc, 0x4b, 0x2b, 0x1f, 0x9b, 0x2a, 0x56, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x0b, 0x5b, 0x3f, 0xd8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryServiceClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	GetEventsStream(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (QueryService_GetEventsStreamClient, error)
}

type queryServiceClient struct {
	cc *grpc.ClientConn
}

func NewQueryServiceClient(cc *grpc.ClientConn) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/queryserver.QueryService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetEventsStream(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (QueryService_GetEventsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QueryService_serviceDesc.Streams[0], "/queryserver.QueryService/GetEventsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryServiceGetEventsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueryService_GetEventsStreamClient interface {
	Recv() (*DetectionEvent, error)
	grpc.ClientStream
}

type queryServiceGetEventsStreamClient struct {
	grpc.ClientStream
}

func (x *queryServiceGetEventsStreamClient) Recv() (*DetectionEvent, error) {
	m := new(DetectionEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QueryServiceServer is the server API for QueryService service.
type QueryServiceServer interface {
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	GetEventsStream(*GetEventsRequest, QueryService_GetEventsStreamServer) error
}

// UnimplementedQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (*UnimplementedQueryServiceServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedQueryServiceServer) GetEventsStream(req *GetEventsRequest, srv QueryService_GetEventsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEventsStream not implemented")
}

func RegisterQueryServiceServer(s *grpc.Server, srv QueryServiceServer) {
	s.RegisterService(&_QueryService_serviceDesc, srv)
}

func _QueryService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queryserver.QueryService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetEventsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).GetEventsStream(m, &queryServiceGetEventsStreamServer{stream})
}

type QueryService_GetEventsStreamServer interface {
	Send(*DetectionEvent) error
	grpc.ServerStream
}

type queryServiceGetEventsStreamServer struct {
	grpc.ServerStream
}

func (x *queryServiceGetEventsStreamServer) Send(m *DetectionEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _QueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "queryserver.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _QueryService_GetEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEventsStream",
			Handler:       _QueryService_GetEventsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "query.proto",
}
