// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collector.proto

package collector

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DEVICE int32

const (
	DEVICE_DEVICE_UNKNOWN DEVICE = 0
	DEVICE_MOBILE         DEVICE = 1
	DEVICE_WIFI           DEVICE = 2
	DEVICE_BLUETOOTH      DEVICE = 3
)

var DEVICE_name = map[int32]string{
	0: "DEVICE_UNKNOWN",
	1: "MOBILE",
	2: "WIFI",
	3: "BLUETOOTH",
}

var DEVICE_value = map[string]int32{
	"DEVICE_UNKNOWN": 0,
	"MOBILE":         1,
	"WIFI":           2,
	"BLUETOOTH":      3,
}

func (x DEVICE) String() string {
	return proto.EnumName(DEVICE_name, int32(x))
}

func (DEVICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{0}
}

type DetectorStatus struct {
	Loc                  *Coordinates    `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	ActiveDetectors      []DEVICE        `protobuf:"varint,2,rep,packed,name=active_detectors,json=activeDetectors,proto3,enum=collector.DEVICE" json:"active_detectors,omitempty"`
	BatteryVoltage       float64         `protobuf:"fixed64,3,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`
	DetectionCount       map[int32]int64 `protobuf:"bytes,4,rep,name=detection_count,json=detectionCount,proto3" json:"detection_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DetectorStatus) Reset()         { *m = DetectorStatus{} }
func (m *DetectorStatus) String() string { return proto.CompactTextString(m) }
func (*DetectorStatus) ProtoMessage()    {}
func (*DetectorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{0}
}

func (m *DetectorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorStatus.Unmarshal(m, b)
}
func (m *DetectorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorStatus.Marshal(b, m, deterministic)
}
func (m *DetectorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorStatus.Merge(m, src)
}
func (m *DetectorStatus) XXX_Size() int {
	return xxx_messageInfo_DetectorStatus.Size(m)
}
func (m *DetectorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorStatus proto.InternalMessageInfo

func (m *DetectorStatus) GetLoc() *Coordinates {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *DetectorStatus) GetActiveDetectors() []DEVICE {
	if m != nil {
		return m.ActiveDetectors
	}
	return nil
}

func (m *DetectorStatus) GetBatteryVoltage() float64 {
	if m != nil {
		return m.BatteryVoltage
	}
	return 0
}

func (m *DetectorStatus) GetDetectionCount() map[int32]int64 {
	if m != nil {
		return m.DetectionCount
	}
	return nil
}

type DetectionEvent struct {
	Time []*timestamp.Timestamp `protobuf:"bytes,1,rep,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to DeviceId:
	//	*DetectionEvent_WifiMac
	//	*DetectionEvent_BluetoothMac
	//	*DetectionEvent_MobileImei
	DeviceId             isDetectionEvent_DeviceId `protobuf_oneof:"device_id"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DetectionEvent) Reset()         { *m = DetectionEvent{} }
func (m *DetectionEvent) String() string { return proto.CompactTextString(m) }
func (*DetectionEvent) ProtoMessage()    {}
func (*DetectionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{1}
}

func (m *DetectionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionEvent.Unmarshal(m, b)
}
func (m *DetectionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionEvent.Marshal(b, m, deterministic)
}
func (m *DetectionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionEvent.Merge(m, src)
}
func (m *DetectionEvent) XXX_Size() int {
	return xxx_messageInfo_DetectionEvent.Size(m)
}
func (m *DetectionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionEvent proto.InternalMessageInfo

func (m *DetectionEvent) GetTime() []*timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type isDetectionEvent_DeviceId interface {
	isDetectionEvent_DeviceId()
}

type DetectionEvent_WifiMac struct {
	WifiMac string `protobuf:"bytes,2,opt,name=wifi_mac,json=wifiMac,proto3,oneof"`
}

type DetectionEvent_BluetoothMac struct {
	BluetoothMac string `protobuf:"bytes,3,opt,name=bluetooth_mac,json=bluetoothMac,proto3,oneof"`
}

type DetectionEvent_MobileImei struct {
	MobileImei string `protobuf:"bytes,4,opt,name=mobile_imei,json=mobileImei,proto3,oneof"`
}

func (*DetectionEvent_WifiMac) isDetectionEvent_DeviceId() {}

func (*DetectionEvent_BluetoothMac) isDetectionEvent_DeviceId() {}

func (*DetectionEvent_MobileImei) isDetectionEvent_DeviceId() {}

func (m *DetectionEvent) GetDeviceId() isDetectionEvent_DeviceId {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *DetectionEvent) GetWifiMac() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_WifiMac); ok {
		return x.WifiMac
	}
	return ""
}

func (m *DetectionEvent) GetBluetoothMac() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_BluetoothMac); ok {
		return x.BluetoothMac
	}
	return ""
}

func (m *DetectionEvent) GetMobileImei() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_MobileImei); ok {
		return x.MobileImei
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DetectionEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DetectionEvent_WifiMac)(nil),
		(*DetectionEvent_BluetoothMac)(nil),
		(*DetectionEvent_MobileImei)(nil),
	}
}

type Coordinates struct {
	DetectorId           string   `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{2}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetDetectorId() string {
	if m != nil {
		return m.DetectorId
	}
	return ""
}

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type EventLog struct {
	Loc                  *Coordinates      `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	Events               []*DetectionEvent `protobuf:"bytes,20,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventLog) Reset()         { *m = EventLog{} }
func (m *EventLog) String() string { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()    {}
func (*EventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{3}
}

func (m *EventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLog.Unmarshal(m, b)
}
func (m *EventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLog.Marshal(b, m, deterministic)
}
func (m *EventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLog.Merge(m, src)
}
func (m *EventLog) XXX_Size() int {
	return xxx_messageInfo_EventLog.Size(m)
}
func (m *EventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLog.DiscardUnknown(m)
}

var xxx_messageInfo_EventLog proto.InternalMessageInfo

func (m *EventLog) GetLoc() *Coordinates {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *EventLog) GetEvents() []*DetectionEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type SendStreamResponse struct {
	Mobile               int64    `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Bluetooth            int64    `protobuf:"varint,3,opt,name=bluetooth,proto3" json:"bluetooth,omitempty"`
	Wifi                 int64    `protobuf:"varint,4,opt,name=wifi,proto3" json:"wifi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStreamResponse) Reset()         { *m = SendStreamResponse{} }
func (m *SendStreamResponse) String() string { return proto.CompactTextString(m) }
func (*SendStreamResponse) ProtoMessage()    {}
func (*SendStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{4}
}

func (m *SendStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStreamResponse.Unmarshal(m, b)
}
func (m *SendStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStreamResponse.Marshal(b, m, deterministic)
}
func (m *SendStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStreamResponse.Merge(m, src)
}
func (m *SendStreamResponse) XXX_Size() int {
	return xxx_messageInfo_SendStreamResponse.Size(m)
}
func (m *SendStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendStreamResponse proto.InternalMessageInfo

func (m *SendStreamResponse) GetMobile() int64 {
	if m != nil {
		return m.Mobile
	}
	return 0
}

func (m *SendStreamResponse) GetBluetooth() int64 {
	if m != nil {
		return m.Bluetooth
	}
	return 0
}

func (m *SendStreamResponse) GetWifi() int64 {
	if m != nil {
		return m.Wifi
	}
	return 0
}

func init() {
	proto.RegisterEnum("collector.DEVICE", DEVICE_name, DEVICE_value)
	proto.RegisterType((*DetectorStatus)(nil), "collector.DetectorStatus")
	proto.RegisterMapType((map[int32]int64)(nil), "collector.DetectorStatus.DetectionCountEntry")
	proto.RegisterType((*DetectionEvent)(nil), "collector.DetectionEvent")
	proto.RegisterType((*Coordinates)(nil), "collector.Coordinates")
	proto.RegisterType((*EventLog)(nil), "collector.EventLog")
	proto.RegisterType((*SendStreamResponse)(nil), "collector.SendStreamResponse")
}

func init() { proto.RegisterFile("collector.proto", fileDescriptor_9305884a292fdf82) }

var fileDescriptor_9305884a292fdf82 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0x8d, 0x31, 0xe1, 0x07, 0x43, 0x02, 0xfe, 0x4d, 0xa2, 0xc8, 0x71, 0x5a, 0x85, 0x22, 0x55,
	0xb5, 0x2a, 0x95, 0xa8, 0xe4, 0x52, 0x55, 0x3d, 0x34, 0x21, 0xae, 0x82, 0x9a, 0x84, 0x6a, 0xc9,
	0x9f, 0x5b, 0x2d, 0x63, 0x6f, 0xc8, 0xaa, 0xb6, 0x17, 0xd9, 0x0b, 0x15, 0x5f, 0xa4, 0x9f, 0xa4,
	0xc7, 0x7e, 0xb8, 0xca, 0xbb, 0x36, 0x90, 0xa6, 0x1c, 0x7a, 0xdb, 0x79, 0xf3, 0x76, 0x76, 0xe6,
	0xbd, 0xb1, 0xa1, 0xe9, 0xf3, 0x30, 0xa4, 0xbe, 0xe0, 0x49, 0x67, 0x92, 0x70, 0xc1, 0xb1, 0xb6,
	0x00, 0xac, 0xc3, 0x31, 0xe7, 0xe3, 0x90, 0x1e, 0xc9, 0xc4, 0x68, 0x7a, 0x7f, 0x24, 0x58, 0x44,
	0x53, 0xe1, 0x45, 0x13, 0xc5, 0xb5, 0x0e, 0xfe, 0x24, 0xd0, 0x68, 0x22, 0xe6, 0x2a, 0xd9, 0xfe,
	0x55, 0x82, 0xc6, 0x19, 0x15, 0xb2, 0xd4, 0x50, 0x78, 0x62, 0x9a, 0xa2, 0x0d, 0x7a, 0xc8, 0x7d,
	0x53, 0x6b, 0x69, 0x76, 0xbd, 0xbb, 0xd7, 0x59, 0x3e, 0xdd, 0xe3, 0x3c, 0x09, 0x58, 0xec, 0x09,
	0x9a, 0x92, 0x8c, 0x82, 0x1f, 0xc0, 0xf0, 0x7c, 0xc1, 0x66, 0xd4, 0x0d, 0xf2, 0x12, 0xa9, 0x59,
	0x6a, 0xe9, 0x76, 0xa3, 0xfb, 0xff, 0xca, 0xb5, 0x33, 0xe7, 0xb6, 0xdf, 0x73, 0x48, 0x53, 0x51,
	0x8b, 0xc7, 0x52, 0x7c, 0x05, 0xcd, 0x91, 0x27, 0x04, 0x4d, 0xe6, 0xee, 0x8c, 0x87, 0xc2, 0x1b,
	0x53, 0x53, 0x6f, 0x69, 0xb6, 0x46, 0x1a, 0x39, 0x7c, 0xab, 0x50, 0xbc, 0x85, 0xa6, 0xaa, 0xcf,
	0x78, 0xec, 0xfa, 0x7c, 0x1a, 0x0b, 0xb3, 0xdc, 0xd2, 0xed, 0x7a, 0xf7, 0xcd, 0xea, 0x2b, 0x8f,
	0x86, 0xc8, 0x43, 0xc6, 0xe3, 0x5e, 0xc6, 0x77, 0x62, 0x91, 0xcc, 0x49, 0x23, 0x78, 0x04, 0x5a,
	0x27, 0xb0, 0xf3, 0x17, 0x1a, 0x1a, 0xa0, 0x7f, 0xa3, 0x73, 0x39, 0xff, 0x26, 0xc9, 0x8e, 0xb8,
	0x0b, 0x9b, 0x33, 0x2f, 0x9c, 0x52, 0xb3, 0xd4, 0xd2, 0x6c, 0x9d, 0xa8, 0xe0, 0x7d, 0xe9, 0x9d,
	0xd6, 0xfe, 0xa9, 0x15, 0xf2, 0x31, 0x1e, 0x3b, 0x33, 0x1a, 0x0b, 0xec, 0x40, 0x39, 0x73, 0xc0,
	0xd4, 0x64, 0x8b, 0x56, 0x47, 0xa9, 0xdf, 0x29, 0xd4, 0xef, 0x5c, 0x17, 0xf6, 0x10, 0xc9, 0xc3,
	0x03, 0xa8, 0x7e, 0x67, 0xf7, 0xcc, 0x8d, 0x3c, 0x5f, 0xd6, 0xaf, 0x9d, 0x6f, 0x90, 0xff, 0x32,
	0xe4, 0xd2, 0xf3, 0xf1, 0x25, 0x6c, 0x8f, 0xc2, 0x29, 0x15, 0x9c, 0x8b, 0x07, 0xc9, 0xd0, 0x73,
	0xc6, 0xd6, 0x02, 0xce, 0x68, 0x2f, 0xa0, 0x1e, 0xf1, 0x11, 0x0b, 0xa9, 0xcb, 0x22, 0xca, 0xcc,
	0x72, 0x4e, 0x02, 0x05, 0xf6, 0x23, 0xca, 0x4e, 0xeb, 0x50, 0x0b, 0xe8, 0x8c, 0xf9, 0xd4, 0x65,
	0x41, 0xfb, 0x01, 0xea, 0x2b, 0x66, 0xe2, 0x21, 0xd4, 0x0b, 0x03, 0x5d, 0x16, 0xc8, 0xc9, 0x6b,
	0x04, 0x0a, 0xa8, 0x1f, 0xa0, 0x05, 0xd5, 0xd0, 0x13, 0x4c, 0x4c, 0x03, 0xa5, 0x81, 0x46, 0x16,
	0x31, 0x3e, 0x83, 0x5a, 0xc8, 0xe3, 0xb1, 0x4a, 0x2a, 0x03, 0x97, 0x40, 0x7b, 0x0c, 0x55, 0x29,
	0xcb, 0x05, 0x1f, 0xff, 0xc3, 0x62, 0xbd, 0x85, 0x0a, 0xcd, 0x6e, 0xa5, 0xe6, 0xae, 0x54, 0x71,
	0xff, 0x89, 0xd1, 0x85, 0xdc, 0x24, 0x27, 0xb6, 0xbf, 0x02, 0x0e, 0x69, 0x1c, 0x0c, 0x45, 0x42,
	0xbd, 0x88, 0xd0, 0x74, 0xc2, 0xe3, 0x94, 0xe2, 0x1e, 0x54, 0x94, 0x06, 0xb9, 0x75, 0x79, 0x94,
	0x35, 0xbd, 0x10, 0x50, 0x36, 0xad, 0x93, 0x25, 0x80, 0x08, 0xe5, 0xcc, 0x00, 0xa9, 0xa3, 0x4e,
	0xe4, 0xf9, 0xf5, 0x09, 0x54, 0xd4, 0x22, 0x23, 0x42, 0x43, 0x9d, 0xdc, 0x9b, 0xab, 0xcf, 0x57,
	0x83, 0xbb, 0x2b, 0x63, 0x03, 0x01, 0x2a, 0x97, 0x83, 0xd3, 0xfe, 0x85, 0x63, 0x68, 0x58, 0x85,
	0xf2, 0x5d, 0xff, 0x53, 0xdf, 0x28, 0xe1, 0x36, 0xd4, 0x4e, 0x2f, 0x6e, 0x9c, 0xeb, 0xc1, 0xe0,
	0xfa, 0xdc, 0xd0, 0xbb, 0x3f, 0x4a, 0x60, 0xf4, 0x8a, 0x39, 0x86, 0x34, 0xc9, 0xdc, 0xc0, 0x63,
	0x28, 0x67, 0x7d, 0xe3, 0xce, 0xca, 0x88, 0x85, 0x62, 0xd6, 0xde, 0x93, 0xed, 0x71, 0xb2, 0x6f,
	0x17, 0xcf, 0x01, 0x96, 0xc3, 0xe2, 0x7a, 0x75, 0xac, 0xe7, 0x2b, 0xa9, 0xa7, 0xf2, 0xd8, 0x1a,
	0x7e, 0x84, 0x06, 0xa1, 0x13, 0x9e, 0x88, 0x2f, 0x3c, 0x65, 0xd9, 0x3d, 0x5c, 0x63, 0xcc, 0xda,
	0x5e, 0x4e, 0x60, 0x4b, 0x55, 0xc8, 0x7f, 0x1f, 0xfb, 0x6b, 0x3f, 0xca, 0x75, 0x25, 0x46, 0x15,
	0x19, 0x1f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xa9, 0xd7, 0xb7, 0xe7, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectorServiceClient interface {
	Send(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*empty.Empty, error)
	SendStream(ctx context.Context, opts ...grpc.CallOption) (CollectorService_SendStreamClient, error)
	ReportPosition(ctx context.Context, in *Coordinates, opts ...grpc.CallOption) (*empty.Empty, error)
	ReportStatus(ctx context.Context, in *DetectorStatus, opts ...grpc.CallOption) (*empty.Empty, error)
}

type collectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCollectorServiceClient(cc *grpc.ClientConn) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) Send(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/collector.CollectorService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (CollectorService_SendStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CollectorService_serviceDesc.Streams[0], "/collector.CollectorService/SendStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorServiceSendStreamClient{stream}
	return x, nil
}

type CollectorService_SendStreamClient interface {
	Send(*DetectionEvent) error
	CloseAndRecv() (*SendStreamResponse, error)
	grpc.ClientStream
}

type collectorServiceSendStreamClient struct {
	grpc.ClientStream
}

func (x *collectorServiceSendStreamClient) Send(m *DetectionEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collectorServiceSendStreamClient) CloseAndRecv() (*SendStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorServiceClient) ReportPosition(ctx context.Context, in *Coordinates, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/collector.CollectorService/ReportPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) ReportStatus(ctx context.Context, in *DetectorStatus, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/collector.CollectorService/ReportStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
type CollectorServiceServer interface {
	Send(context.Context, *EventLog) (*empty.Empty, error)
	SendStream(CollectorService_SendStreamServer) error
	ReportPosition(context.Context, *Coordinates) (*empty.Empty, error)
	ReportStatus(context.Context, *DetectorStatus) (*empty.Empty, error)
}

// UnimplementedCollectorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCollectorServiceServer struct {
}

func (*UnimplementedCollectorServiceServer) Send(ctx context.Context, req *EventLog) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedCollectorServiceServer) SendStream(srv CollectorService_SendStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStream not implemented")
}
func (*UnimplementedCollectorServiceServer) ReportPosition(ctx context.Context, req *Coordinates) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPosition not implemented")
}
func (*UnimplementedCollectorServiceServer) ReportStatus(ctx context.Context, req *DetectorStatus) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}

func RegisterCollectorServiceServer(s *grpc.Server, srv CollectorServiceServer) {
	s.RegisterService(&_CollectorService_serviceDesc, srv)
}

func _CollectorService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Send(ctx, req.(*EventLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).SendStream(&collectorServiceSendStreamServer{stream})
}

type CollectorService_SendStreamServer interface {
	SendAndClose(*SendStreamResponse) error
	Recv() (*DetectionEvent, error)
	grpc.ServerStream
}

type collectorServiceSendStreamServer struct {
	grpc.ServerStream
}

func (x *collectorServiceSendStreamServer) SendAndClose(m *SendStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collectorServiceSendStreamServer) Recv() (*DetectionEvent, error) {
	m := new(DetectionEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CollectorService_ReportPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Coordinates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ReportPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/ReportPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ReportPosition(ctx, req.(*Coordinates))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectorStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/ReportStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ReportStatus(ctx, req.(*DetectorStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _CollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "collector.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _CollectorService_Send_Handler,
		},
		{
			MethodName: "ReportPosition",
			Handler:    _CollectorService_ReportPosition_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _CollectorService_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _CollectorService_SendStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "collector.proto",
}
