// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collector.proto

package collector

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DEVICE int32

const (
	DEVICE_DEVICE_UNKNOWN DEVICE = 0
	DEVICE_MOBILE         DEVICE = 1
	DEVICE_WIFI           DEVICE = 2
	DEVICE_BLUETOOTH      DEVICE = 3
)

var DEVICE_name = map[int32]string{
	0: "DEVICE_UNKNOWN",
	1: "MOBILE",
	2: "WIFI",
	3: "BLUETOOTH",
}

var DEVICE_value = map[string]int32{
	"DEVICE_UNKNOWN": 0,
	"MOBILE":         1,
	"WIFI":           2,
	"BLUETOOTH":      3,
}

func (x DEVICE) String() string {
	return proto.EnumName(DEVICE_name, int32(x))
}

func (DEVICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{0}
}

type DetectorStatus struct {
	Loc                  *Coordinates    `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	ActiveDetectors      []DEVICE        `protobuf:"varint,2,rep,packed,name=active_detectors,json=activeDetectors,proto3,enum=collector.DEVICE" json:"active_detectors,omitempty"`
	BatteryVoltage       float64         `protobuf:"fixed64,3,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`
	DetectionCount       map[int32]int64 `protobuf:"bytes,4,rep,name=detection_count,json=detectionCount,proto3" json:"detection_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DetectorStatus) Reset()         { *m = DetectorStatus{} }
func (m *DetectorStatus) String() string { return proto.CompactTextString(m) }
func (*DetectorStatus) ProtoMessage()    {}
func (*DetectorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{0}
}

func (m *DetectorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorStatus.Unmarshal(m, b)
}
func (m *DetectorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorStatus.Marshal(b, m, deterministic)
}
func (m *DetectorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorStatus.Merge(m, src)
}
func (m *DetectorStatus) XXX_Size() int {
	return xxx_messageInfo_DetectorStatus.Size(m)
}
func (m *DetectorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorStatus proto.InternalMessageInfo

func (m *DetectorStatus) GetLoc() *Coordinates {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *DetectorStatus) GetActiveDetectors() []DEVICE {
	if m != nil {
		return m.ActiveDetectors
	}
	return nil
}

func (m *DetectorStatus) GetBatteryVoltage() float64 {
	if m != nil {
		return m.BatteryVoltage
	}
	return 0
}

func (m *DetectorStatus) GetDetectionCount() map[int32]int64 {
	if m != nil {
		return m.DetectionCount
	}
	return nil
}

type DetectionEvent struct {
	Time []*timestamp.Timestamp `protobuf:"bytes,1,rep,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to DeviceId:
	//	*DetectionEvent_Wifi
	//	*DetectionEvent_Bluetooth
	//	*DetectionEvent_Mobile
	DeviceId             isDetectionEvent_DeviceId `protobuf_oneof:"device_id"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DetectionEvent) Reset()         { *m = DetectionEvent{} }
func (m *DetectionEvent) String() string { return proto.CompactTextString(m) }
func (*DetectionEvent) ProtoMessage()    {}
func (*DetectionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{1}
}

func (m *DetectionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionEvent.Unmarshal(m, b)
}
func (m *DetectionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionEvent.Marshal(b, m, deterministic)
}
func (m *DetectionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionEvent.Merge(m, src)
}
func (m *DetectionEvent) XXX_Size() int {
	return xxx_messageInfo_DetectionEvent.Size(m)
}
func (m *DetectionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionEvent proto.InternalMessageInfo

func (m *DetectionEvent) GetTime() []*timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type isDetectionEvent_DeviceId interface {
	isDetectionEvent_DeviceId()
}

type DetectionEvent_Wifi struct {
	Wifi string `protobuf:"bytes,2,opt,name=wifi,proto3,oneof"`
}

type DetectionEvent_Bluetooth struct {
	Bluetooth string `protobuf:"bytes,3,opt,name=bluetooth,proto3,oneof"`
}

type DetectionEvent_Mobile struct {
	Mobile string `protobuf:"bytes,4,opt,name=mobile,proto3,oneof"`
}

func (*DetectionEvent_Wifi) isDetectionEvent_DeviceId() {}

func (*DetectionEvent_Bluetooth) isDetectionEvent_DeviceId() {}

func (*DetectionEvent_Mobile) isDetectionEvent_DeviceId() {}

func (m *DetectionEvent) GetDeviceId() isDetectionEvent_DeviceId {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *DetectionEvent) GetWifi() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_Wifi); ok {
		return x.Wifi
	}
	return ""
}

func (m *DetectionEvent) GetBluetooth() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_Bluetooth); ok {
		return x.Bluetooth
	}
	return ""
}

func (m *DetectionEvent) GetMobile() string {
	if x, ok := m.GetDeviceId().(*DetectionEvent_Mobile); ok {
		return x.Mobile
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DetectionEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DetectionEvent_Wifi)(nil),
		(*DetectionEvent_Bluetooth)(nil),
		(*DetectionEvent_Mobile)(nil),
	}
}

type Coordinates struct {
	DetectorId           string   `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{2}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetDetectorId() string {
	if m != nil {
		return m.DetectorId
	}
	return ""
}

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type EventLog struct {
	Loc                  *Coordinates      `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	Events               []*DetectionEvent `protobuf:"bytes,20,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventLog) Reset()         { *m = EventLog{} }
func (m *EventLog) String() string { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()    {}
func (*EventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{3}
}

func (m *EventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLog.Unmarshal(m, b)
}
func (m *EventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLog.Marshal(b, m, deterministic)
}
func (m *EventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLog.Merge(m, src)
}
func (m *EventLog) XXX_Size() int {
	return xxx_messageInfo_EventLog.Size(m)
}
func (m *EventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLog.DiscardUnknown(m)
}

var xxx_messageInfo_EventLog proto.InternalMessageInfo

func (m *EventLog) GetLoc() *Coordinates {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *EventLog) GetEvents() []*DetectionEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type SendStreamResponse struct {
	Mobile               int64    `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Bluetooth            int64    `protobuf:"varint,3,opt,name=bluetooth,proto3" json:"bluetooth,omitempty"`
	Wifi                 int64    `protobuf:"varint,4,opt,name=wifi,proto3" json:"wifi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStreamResponse) Reset()         { *m = SendStreamResponse{} }
func (m *SendStreamResponse) String() string { return proto.CompactTextString(m) }
func (*SendStreamResponse) ProtoMessage()    {}
func (*SendStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{4}
}

func (m *SendStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStreamResponse.Unmarshal(m, b)
}
func (m *SendStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStreamResponse.Marshal(b, m, deterministic)
}
func (m *SendStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStreamResponse.Merge(m, src)
}
func (m *SendStreamResponse) XXX_Size() int {
	return xxx_messageInfo_SendStreamResponse.Size(m)
}
func (m *SendStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendStreamResponse proto.InternalMessageInfo

func (m *SendStreamResponse) GetMobile() int64 {
	if m != nil {
		return m.Mobile
	}
	return 0
}

func (m *SendStreamResponse) GetBluetooth() int64 {
	if m != nil {
		return m.Bluetooth
	}
	return 0
}

func (m *SendStreamResponse) GetWifi() int64 {
	if m != nil {
		return m.Wifi
	}
	return 0
}

func init() {
	proto.RegisterEnum("collector.DEVICE", DEVICE_name, DEVICE_value)
	proto.RegisterType((*DetectorStatus)(nil), "collector.DetectorStatus")
	proto.RegisterMapType((map[int32]int64)(nil), "collector.DetectorStatus.DetectionCountEntry")
	proto.RegisterType((*DetectionEvent)(nil), "collector.DetectionEvent")
	proto.RegisterType((*Coordinates)(nil), "collector.Coordinates")
	proto.RegisterType((*EventLog)(nil), "collector.EventLog")
	proto.RegisterType((*SendStreamResponse)(nil), "collector.SendStreamResponse")
}

func init() { proto.RegisterFile("collector.proto", fileDescriptor_9305884a292fdf82) }

var fileDescriptor_9305884a292fdf82 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x6e, 0xda, 0x40,
	0x10, 0x8d, 0x31, 0x41, 0xf1, 0xa0, 0x1a, 0x67, 0x82, 0x22, 0x87, 0x5e, 0x82, 0x78, 0xa9, 0x55,
	0xa9, 0x44, 0xa5, 0x2f, 0x55, 0xd5, 0x3e, 0x24, 0xc4, 0x51, 0x50, 0xd3, 0x20, 0x99, 0x5c, 0xde,
	0x8a, 0x0c, 0x9e, 0x90, 0x55, 0x8d, 0x17, 0xd9, 0x0b, 0x15, 0x1f, 0xd3, 0x0f, 0xe8, 0x3f, 0xf4,
	0xe3, 0x2a, 0xef, 0xda, 0xc4, 0x09, 0xa5, 0x52, 0xdf, 0x76, 0xce, 0x9c, 0x9d, 0xdd, 0x73, 0xce,
	0xda, 0x50, 0x1b, 0xf3, 0x30, 0xa4, 0xb1, 0xe0, 0x71, 0x7b, 0x16, 0x73, 0xc1, 0xd1, 0x58, 0x01,
	0x8d, 0xc3, 0x09, 0xe7, 0x93, 0x90, 0x8e, 0x64, 0x63, 0x34, 0xbf, 0x3b, 0x12, 0x6c, 0x4a, 0x89,
	0xf0, 0xa7, 0x33, 0xc5, 0x6d, 0x3c, 0x7f, 0x4a, 0xa0, 0xe9, 0x4c, 0x2c, 0x55, 0xb3, 0xf5, 0xbb,
	0x04, 0xe6, 0x29, 0x09, 0x39, 0x6a, 0x20, 0x7c, 0x31, 0x4f, 0xd0, 0x01, 0x3d, 0xe4, 0x63, 0x5b,
	0x6b, 0x6a, 0x4e, 0xb5, 0xb3, 0xdf, 0x7e, 0x38, 0xba, 0xcb, 0x79, 0x1c, 0xb0, 0xc8, 0x17, 0x94,
	0x78, 0x29, 0x05, 0x3f, 0x81, 0xe5, 0x8f, 0x05, 0x5b, 0xd0, 0x30, 0xc8, 0x46, 0x24, 0x76, 0xa9,
	0xa9, 0x3b, 0x66, 0x67, 0xb7, 0xb0, 0xed, 0xd4, 0xbd, 0xe9, 0x75, 0x5d, 0xaf, 0xa6, 0xa8, 0xf9,
	0x61, 0x09, 0xbe, 0x86, 0xda, 0xc8, 0x17, 0x82, 0xe2, 0xe5, 0x70, 0xc1, 0x43, 0xe1, 0x4f, 0xc8,
	0xd6, 0x9b, 0x9a, 0xa3, 0x79, 0x66, 0x06, 0xdf, 0x28, 0x14, 0x6f, 0xa0, 0xa6, 0xe6, 0x33, 0x1e,
	0x0d, 0xc7, 0x7c, 0x1e, 0x09, 0xbb, 0xdc, 0xd4, 0x9d, 0x6a, 0xe7, 0x6d, 0xf1, 0x94, 0x47, 0x22,
	0xb2, 0x92, 0xf1, 0xa8, 0x9b, 0xf2, 0xdd, 0x48, 0xc4, 0x4b, 0xcf, 0x0c, 0x1e, 0x81, 0x8d, 0x63,
	0xd8, 0xfb, 0x0b, 0x0d, 0x2d, 0xd0, 0xbf, 0xd3, 0x52, 0xea, 0xdf, 0xf6, 0xd2, 0x25, 0xd6, 0x61,
	0x7b, 0xe1, 0x87, 0x73, 0xb2, 0x4b, 0x4d, 0xcd, 0xd1, 0x3d, 0x55, 0x7c, 0x2c, 0x7d, 0xd0, 0x5a,
	0x3f, 0xb5, 0xdc, 0x3e, 0xc6, 0x23, 0x77, 0x41, 0x91, 0xc0, 0x36, 0x94, 0xd3, 0x04, 0x6c, 0x4d,
	0x5e, 0xb1, 0xd1, 0x56, 0xee, 0xb7, 0x73, 0xf7, 0xdb, 0x57, 0x79, 0x3c, 0x9e, 0xe4, 0x61, 0x1d,
	0xca, 0x3f, 0xd8, 0x1d, 0x93, 0xb3, 0x8d, 0xf3, 0x2d, 0x4f, 0x56, 0xf8, 0x0a, 0x8c, 0x51, 0x38,
	0x27, 0xc1, 0xb9, 0xb8, 0x97, 0xb6, 0xa4, 0xad, 0x07, 0x08, 0x6d, 0xa8, 0x4c, 0xf9, 0x88, 0x85,
	0x64, 0x97, 0xb3, 0x66, 0x56, 0x9f, 0x54, 0xc1, 0x08, 0x68, 0xc1, 0xc6, 0x34, 0x64, 0x41, 0xeb,
	0x1e, 0xaa, 0x85, 0xd4, 0xf0, 0x10, 0xaa, 0x79, 0x52, 0x43, 0x16, 0x48, 0x89, 0x86, 0x07, 0x39,
	0xd4, 0x0b, 0xb0, 0x01, 0x3b, 0xa1, 0x2f, 0x98, 0x98, 0x07, 0x4a, 0xac, 0xe6, 0xad, 0x6a, 0x7c,
	0x01, 0x46, 0xc8, 0xa3, 0x89, 0x6a, 0xaa, 0xa4, 0x1e, 0x80, 0xd6, 0x04, 0x76, 0xa4, 0xfe, 0x0b,
	0x3e, 0xf9, 0x8f, 0x17, 0xf4, 0x0e, 0x2a, 0x94, 0xee, 0x4a, 0xec, 0xba, 0xb4, 0xeb, 0x60, 0x2d,
	0xd1, 0xdc, 0x57, 0x2f, 0x23, 0xb6, 0xbe, 0x01, 0x0e, 0x28, 0x0a, 0x06, 0x22, 0x26, 0x7f, 0xea,
	0x51, 0x32, 0xe3, 0x51, 0x42, 0xb8, 0xbf, 0xf2, 0x43, 0x65, 0x94, 0x55, 0xe9, 0xa5, 0x1f, 0xfb,
	0xa8, 0x17, 0x5d, 0xc4, 0xcc, 0xfb, 0xb2, 0x6c, 0xc8, 0xf5, 0x9b, 0x63, 0xa8, 0xa8, 0x17, 0x8b,
	0x08, 0xa6, 0x5a, 0x0d, 0xaf, 0x2f, 0xbf, 0x5c, 0xf6, 0x6f, 0x2f, 0xad, 0x2d, 0x04, 0xa8, 0x7c,
	0xed, 0x9f, 0xf4, 0x2e, 0x5c, 0x4b, 0xc3, 0x1d, 0x28, 0xdf, 0xf6, 0xce, 0x7a, 0x56, 0x09, 0x9f,
	0x81, 0x71, 0x72, 0x71, 0xed, 0x5e, 0xf5, 0xfb, 0x57, 0xe7, 0x96, 0xde, 0xf9, 0x55, 0x02, 0xab,
	0x9b, 0xeb, 0x18, 0x50, 0x9c, 0xa6, 0x81, 0x9f, 0xc1, 0xec, 0xc6, 0xe4, 0x0b, 0x5a, 0xd9, 0xb4,
	0x57, 0x10, 0x9b, 0x83, 0x8d, 0xfd, 0xb5, 0x07, 0xe3, 0xa6, 0x9f, 0x2b, 0x9e, 0x81, 0xa9, 0x24,
	0xff, 0x7b, 0xfb, 0xcb, 0x02, 0xb8, 0x6e, 0x93, 0xa3, 0x61, 0x17, 0x76, 0xd5, 0x35, 0x8a, 0xef,
	0x62, 0x43, 0x46, 0x1b, 0x2f, 0xd3, 0x83, 0xba, 0x1a, 0xf2, 0xe4, 0xd7, 0x71, 0xb0, 0xf1, 0x83,
	0xdc, 0x34, 0x6a, 0x54, 0x91, 0xf5, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0xd9, 0x2c,
	0x92, 0xe3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectorServiceClient interface {
	CreateEventLog(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*empty.Empty, error)
	StreamEventLog(ctx context.Context, opts ...grpc.CallOption) (CollectorService_StreamEventLogClient, error)
	CreateCoordinates(ctx context.Context, in *Coordinates, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateDetectorStatus(ctx context.Context, in *DetectorStatus, opts ...grpc.CallOption) (*empty.Empty, error)
}

type collectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCollectorServiceClient(cc *grpc.ClientConn) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) CreateEventLog(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/collector.CollectorService/CreateEventLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) StreamEventLog(ctx context.Context, opts ...grpc.CallOption) (CollectorService_StreamEventLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CollectorService_serviceDesc.Streams[0], "/collector.CollectorService/StreamEventLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorServiceStreamEventLogClient{stream}
	return x, nil
}

type CollectorService_StreamEventLogClient interface {
	Send(*EventLog) error
	CloseAndRecv() (*SendStreamResponse, error)
	grpc.ClientStream
}

type collectorServiceStreamEventLogClient struct {
	grpc.ClientStream
}

func (x *collectorServiceStreamEventLogClient) Send(m *EventLog) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collectorServiceStreamEventLogClient) CloseAndRecv() (*SendStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorServiceClient) CreateCoordinates(ctx context.Context, in *Coordinates, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/collector.CollectorService/CreateCoordinates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) CreateDetectorStatus(ctx context.Context, in *DetectorStatus, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/collector.CollectorService/CreateDetectorStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
type CollectorServiceServer interface {
	CreateEventLog(context.Context, *EventLog) (*empty.Empty, error)
	StreamEventLog(CollectorService_StreamEventLogServer) error
	CreateCoordinates(context.Context, *Coordinates) (*empty.Empty, error)
	CreateDetectorStatus(context.Context, *DetectorStatus) (*empty.Empty, error)
}

// UnimplementedCollectorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCollectorServiceServer struct {
}

func (*UnimplementedCollectorServiceServer) CreateEventLog(ctx context.Context, req *EventLog) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEventLog not implemented")
}
func (*UnimplementedCollectorServiceServer) StreamEventLog(srv CollectorService_StreamEventLogServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEventLog not implemented")
}
func (*UnimplementedCollectorServiceServer) CreateCoordinates(ctx context.Context, req *Coordinates) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCoordinates not implemented")
}
func (*UnimplementedCollectorServiceServer) CreateDetectorStatus(ctx context.Context, req *DetectorStatus) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDetectorStatus not implemented")
}

func RegisterCollectorServiceServer(s *grpc.Server, srv CollectorServiceServer) {
	s.RegisterService(&_CollectorService_serviceDesc, srv)
}

func _CollectorService_CreateEventLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).CreateEventLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/CreateEventLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).CreateEventLog(ctx, req.(*EventLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_StreamEventLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).StreamEventLog(&collectorServiceStreamEventLogServer{stream})
}

type CollectorService_StreamEventLogServer interface {
	SendAndClose(*SendStreamResponse) error
	Recv() (*EventLog, error)
	grpc.ServerStream
}

type collectorServiceStreamEventLogServer struct {
	grpc.ServerStream
}

func (x *collectorServiceStreamEventLogServer) SendAndClose(m *SendStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collectorServiceStreamEventLogServer) Recv() (*EventLog, error) {
	m := new(EventLog)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CollectorService_CreateCoordinates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Coordinates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).CreateCoordinates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/CreateCoordinates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).CreateCoordinates(ctx, req.(*Coordinates))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_CreateDetectorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectorStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).CreateDetectorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/CreateDetectorStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).CreateDetectorStatus(ctx, req.(*DetectorStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _CollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "collector.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEventLog",
			Handler:    _CollectorService_CreateEventLog_Handler,
		},
		{
			MethodName: "CreateCoordinates",
			Handler:    _CollectorService_CreateCoordinates_Handler,
		},
		{
			MethodName: "CreateDetectorStatus",
			Handler:    _CollectorService_CreateDetectorStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEventLog",
			Handler:       _CollectorService_StreamEventLog_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "collector.proto",
}
