Name: "cqserver"
RepoName: "message_bus"
ImageTag: "v0.0.1"
Registry: "jozuenoon"
Servers: 2
Scheme: "HTTP"
ImagePullPolicy: "IfNotPresent"

# Service
ServiceType: ClusterIP

# Ingress configuration
IngressClass: "nginx"
QueryFQDN: "query.message-bus.traffic"
CollectorFQDN: "collector.message-bus.traffic"
CertManagerEnabled: false

# Pod disruption budget
MinAvailable: 1

# Configuration
ETCDEndpoints: "http://etcd-client:2379"
CollectorPort: 9000
QueryPort: 8000
HealthCheckPort: 5000
