// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DEVICE int32

const (
	DEVICE_DEVICE_UNKNOWN DEVICE = 0
	DEVICE_MOBILE         DEVICE = 1
	DEVICE_WIFI           DEVICE = 2
	DEVICE_BLUETOOTH      DEVICE = 3
)

var DEVICE_name = map[int32]string{
	0: "DEVICE_UNKNOWN",
	1: "MOBILE",
	2: "WIFI",
	3: "BLUETOOTH",
}

var DEVICE_value = map[string]int32{
	"DEVICE_UNKNOWN": 0,
	"MOBILE":         1,
	"WIFI":           2,
	"BLUETOOTH":      3,
}

func (x DEVICE) String() string {
	return proto.EnumName(DEVICE_name, int32(x))
}

func (DEVICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

type DetectionEvent struct {
	DeviceId             string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Type                 DEVICE                 `protobuf:"varint,2,opt,name=type,proto3,enum=api.DEVICE" json:"type,omitempty"`
	Time                 []*timestamp.Timestamp `protobuf:"bytes,3,rep,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DetectionEvent) Reset()         { *m = DetectionEvent{} }
func (m *DetectionEvent) String() string { return proto.CompactTextString(m) }
func (*DetectionEvent) ProtoMessage()    {}
func (*DetectionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *DetectionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionEvent.Unmarshal(m, b)
}
func (m *DetectionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionEvent.Marshal(b, m, deterministic)
}
func (m *DetectionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionEvent.Merge(m, src)
}
func (m *DetectionEvent) XXX_Size() int {
	return xxx_messageInfo_DetectionEvent.Size(m)
}
func (m *DetectionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionEvent proto.InternalMessageInfo

func (m *DetectionEvent) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DetectionEvent) GetType() DEVICE {
	if m != nil {
		return m.Type
	}
	return DEVICE_DEVICE_UNKNOWN
}

func (m *DetectionEvent) GetTime() []*timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Coordinates struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type EventLog struct {
	DetectorId           string            `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	Loc                  *Coordinates      `protobuf:"bytes,2,opt,name=loc,proto3" json:"loc,omitempty"`
	Events               []*DetectionEvent `protobuf:"bytes,20,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventLog) Reset()         { *m = EventLog{} }
func (m *EventLog) String() string { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()    {}
func (*EventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *EventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLog.Unmarshal(m, b)
}
func (m *EventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLog.Marshal(b, m, deterministic)
}
func (m *EventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLog.Merge(m, src)
}
func (m *EventLog) XXX_Size() int {
	return xxx_messageInfo_EventLog.Size(m)
}
func (m *EventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLog.DiscardUnknown(m)
}

var xxx_messageInfo_EventLog proto.InternalMessageInfo

func (m *EventLog) GetDetectorId() string {
	if m != nil {
		return m.DetectorId
	}
	return ""
}

func (m *EventLog) GetLoc() *Coordinates {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *EventLog) GetEvents() []*DetectionEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.DEVICE", DEVICE_name, DEVICE_value)
	proto.RegisterType((*DetectionEvent)(nil), "api.DetectionEvent")
	proto.RegisterType((*Coordinates)(nil), "api.Coordinates")
	proto.RegisterType((*EventLog)(nil), "api.EventLog")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x5d, 0xcb, 0x9b, 0x30,
	0x18, 0x9d, 0xaf, 0x22, 0xfa, 0x48, 0x8b, 0x3c, 0x1b, 0x43, 0x7c, 0x07, 0x2d, 0x5e, 0x95, 0x8d,
	0x59, 0x70, 0xbf, 0xa0, 0x1f, 0x8e, 0xc9, 0xba, 0x0a, 0xb6, 0x5d, 0x2f, 0x76, 0x51, 0x6c, 0x93,
	0x49, 0x40, 0x8d, 0xd8, 0xb4, 0x50, 0x18, 0xfb, 0xed, 0xc3, 0xa4, 0xae, 0xfb, 0xb8, 0x4b, 0xce,
	0x39, 0xe4, 0x7c, 0x04, 0x06, 0x79, 0xc3, 0xa6, 0x79, 0xc3, 0xc2, 0xa6, 0xe5, 0x82, 0xa3, 0x9e,
	0x37, 0xcc, 0x1f, 0x15, 0x9c, 0x17, 0x25, 0x9d, 0x4a, 0xe8, 0x78, 0xf9, 0x3e, 0x15, 0xac, 0xa2,
	0x67, 0x91, 0x57, 0x8d, 0x52, 0xf9, 0xcf, 0xff, 0x0a, 0x68, 0xd5, 0x88, 0x9b, 0x22, 0x83, 0x9f,
	0x30, 0x5c, 0x52, 0x41, 0x4f, 0x82, 0xf1, 0x3a, 0xbe, 0xd2, 0x5a, 0xe0, 0x33, 0xd8, 0x84, 0x5e,
	0xd9, 0x89, 0x1e, 0x18, 0xf1, 0xb4, 0xb1, 0x36, 0xb1, 0x33, 0x4b, 0x01, 0x09, 0xc1, 0x11, 0x18,
	0xe2, 0xd6, 0x50, 0xef, 0x69, 0xac, 0x4d, 0x86, 0x91, 0x13, 0x76, 0x59, 0x96, 0xf1, 0xd7, 0x64,
	0x11, 0x67, 0x92, 0xc0, 0x10, 0x8c, 0xce, 0xdf, 0xd3, 0xc7, 0xfa, 0xc4, 0x89, 0xfc, 0x50, 0x79,
	0x87, 0xbd, 0x77, 0xb8, 0xed, 0xc3, 0x65, 0x52, 0x17, 0x7c, 0x03, 0x67, 0xc1, 0x79, 0x4b, 0x58,
	0x9d, 0x0b, 0x7a, 0x46, 0x04, 0xa3, 0xce, 0x2b, 0x7a, 0xf7, 0x95, 0x67, 0xf4, 0xc1, 0x2a, 0x73,
	0xc1, 0xc4, 0x85, 0x28, 0x5f, 0x2d, 0xfb, 0x7d, 0xc7, 0x37, 0x60, 0x97, 0xbc, 0x2e, 0x14, 0xa9,
	0x4b, 0xf2, 0x01, 0x04, 0x3f, 0xc0, 0x92, 0x9d, 0x56, 0xbc, 0xc0, 0x11, 0x38, 0x44, 0x16, 0xe5,
	0xed, 0xa3, 0x18, 0xf4, 0x50, 0x42, 0x30, 0x00, 0xbd, 0xe4, 0x27, 0xe9, 0xe0, 0x44, 0xae, 0x6c,
	0xf6, 0x47, 0xb2, 0xac, 0x23, 0xf1, 0x1d, 0x98, 0xb4, 0x7b, 0xf0, 0xec, 0xbd, 0x92, 0xfd, 0x5e,
	0xaa, 0x01, 0xfe, 0x1a, 0x30, 0xbb, 0x4b, 0xde, 0xce, 0xc0, 0x54, 0xd3, 0x20, 0xc2, 0x50, 0x9d,
	0x0e, 0xbb, 0xf5, 0xe7, 0x75, 0xba, 0x5f, 0xbb, 0x2f, 0x10, 0xc0, 0xfc, 0x92, 0xce, 0x93, 0x55,
	0xec, 0x6a, 0x68, 0x81, 0xb1, 0x4f, 0x3e, 0x26, 0xee, 0x13, 0x0e, 0xc0, 0x9e, 0xaf, 0x76, 0xf1,
	0x36, 0x4d, 0xb7, 0x9f, 0x5c, 0x3d, 0x9a, 0x81, 0xbb, 0xe0, 0x65, 0x29, 0x23, 0x6e, 0x68, 0xdb,
	0x7d, 0x02, 0xbe, 0x07, 0x63, 0x43, 0x6b, 0x82, 0x03, 0xe9, 0xdd, 0xf7, 0xf3, 0x5f, 0xff, 0x37,
	0x75, 0xdc, 0x7d, 0xf3, 0xd1, 0x94, 0xf7, 0x0f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x45,
	0xd3, 0x7c, 0x3b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectorServiceClient interface {
	Send(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*empty.Empty, error)
}

type collectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCollectorServiceClient(cc *grpc.ClientConn) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) Send(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.CollectorService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
type CollectorServiceServer interface {
	Send(context.Context, *EventLog) (*empty.Empty, error)
}

func RegisterCollectorServiceServer(s *grpc.Server, srv CollectorServiceServer) {
	s.RegisterService(&_CollectorService_serviceDesc, srv)
}

func _CollectorService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CollectorService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Send(ctx, req.(*EventLog))
	}
	return interceptor(ctx, in, info, handler)
}

var _CollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _CollectorService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
